package com.estebvac.urdudeutsch

internal val lessonsOneToFive = listOf(
    Lesson(
        id = 1,
        title = "Schrift und Begrüßungen",
        urduTitle = "سلام اور رسم الخط",
        objective = "Du lernst die Schreibrichtung, Begrüßungen und höfliche Antworten.",
        grammar = "Urdu wird von rechts nach links geschrieben. آپ (āp) ist die höfliche Anrede; ہے (hai) und ہیں (hain) verbinden einfache Aussagen.",
        dialogue = listOf(
            phrase("السلام علیکم", "assalāmu alaikum", "Guten Tag"),
            phrase("وعلیکم السلام", "wa alaikum assalām", "Antwort auf die Begrüßung"),
            phrase("آپ کیسے ہیں؟", "āp kaise hain?", "Wie geht es Ihnen?"),
            phrase("میں ٹھیک ہوں، شکریہ۔", "main ṭhīk hūn, shukriyā.", "Mir geht es gut, danke."),
        ),
        vocabulary = listOf(
            phrase("سلام", "salām", "Hallo"),
            phrase("شکریہ", "shukriyā", "Danke"),
            phrase("جی", "jī", "Ja, höflich"),
            phrase("نہیں", "nahīn", "Nein / nicht"),
            phrase("ٹھیک", "ṭhīk", "gut / in Ordnung"),
            phrase("خدا حافظ", "khudā hāfiz", "Auf Wiedersehen"),
        ),
        questions = listOf(
            question("Was bedeutet شکریہ?", "Danke", "Hallo", "Nein", "شکریہ bedeutet Danke."),
            question("In welche Richtung wird Urdu geschrieben?", "Von rechts nach links", "Von links nach rechts", "Von oben nach unten", "Urdu verwendet eine rechts-nach-links verlaufende Schrift."),
            question("Welche Form ist eine Verabschiedung?", "خدا حافظ", "آپ کیسے ہیں؟", "شکریہ", "خدا حافظ bedeutet Auf Wiedersehen."),
        ),
    ),
    Lesson(
        id = 2,
        title = "Persönliche Informationen",
        urduTitle = "ذاتی معلومات",
        objective = "Du stellst dich vor und sprichst über Name, Herkunft und Sprache.",
        grammar = "میں (main) bedeutet ich. Mit سے (se) wird Herkunft ausgedrückt. Männliche und weibliche Verlaufsformen verwenden رہا beziehungsweise رہی.",
        dialogue = listOf(
            phrase("آپ کا نام کیا ہے؟", "āp kā nām kyā hai?", "Wie heißen Sie?"),
            phrase("میرا نام انا ہے۔", "merā nām Annā hai.", "Ich heiße Anna."),
            phrase("آپ کہاں سے ہیں؟", "āp kahān se hain?", "Woher kommen Sie?"),
            phrase("میں جرمنی سے ہوں۔", "main Jarmanī se hūn.", "Ich komme aus Deutschland."),
        ),
        vocabulary = listOf(
            phrase("نام", "nām", "Name"),
            phrase("ملک", "mulk", "Land"),
            phrase("زبان", "zabān", "Sprache"),
            phrase("جرمنی", "Jarmanī", "Deutschland"),
            phrase("پاکستان", "Pākistān", "Pakistan"),
            phrase("سیکھنا", "sīkhnā", "lernen"),
        ),
        questions = listOf(
            question("Wie fragst du nach dem Namen?", "آپ کا نام کیا ہے؟", "آپ کہاں سے ہیں؟", "آپ کیسے ہیں؟", "نام bedeutet Name."),
            question("Welche Postposition bedeutet hier aus/von?", "سے", "میں", "کا", "Mit سے wird die Herkunft angegeben."),
            question("Was bedeutet زبان?", "Sprache", "Land", "Name", "زبان bedeutet Sprache."),
        ),
    ),
    Lesson(
        id = 3,
        title = "Familie und Besitz",
        urduTitle = "خاندان اور ملکیت",
        objective = "Du benennst Familienmitglieder und verwendest Besitzformen.",
        grammar = "کا، کی und کے verbinden Besitzer und Besitz. Die Form richtet sich nach Geschlecht und Zahl des besessenen Wortes.",
        dialogue = listOf(
            phrase("یہ میری بیٹی ہے۔", "ye merī beṭī hai.", "Das ist meine Tochter."),
            phrase("وہ میرے والد ہیں۔", "wo mere wālid hain.", "Das ist mein Vater."),
            phrase("میری ایک بہن ہے۔", "merī ek behn hai.", "Ich habe eine Schwester."),
            phrase("کیا آپ کے بچے ہیں؟", "kyā āp ke bachche hain?", "Haben Sie Kinder?"),
        ),
        vocabulary = listOf(
            phrase("خاندان", "khāndān", "Familie"),
            phrase("والد", "wālid", "Vater"),
            phrase("والدہ", "wālida", "Mutter"),
            phrase("بیٹا", "beṭā", "Sohn"),
            phrase("بیٹی", "beṭī", "Tochter"),
            phrase("بہن", "behn", "Schwester"),
        ),
        questions = listOf(
            question("Welche Form passt vor بیٹی?", "میری", "میرا", "میرے", "بیٹی ist feminin, daher میری."),
            question("Was bedeutet خاندان?", "Familie", "Freund", "Kind", "خاندان bedeutet Familie."),
            question("Welche Form bedeutet Tochter?", "بیٹی", "بیٹا", "بہن", "بیٹی bedeutet Tochter."),
        ),
    ),
    Lesson(
        id = 4,
        title = "Essen und Trinken",
        urduTitle = "کھانا اور پینا",
        objective = "Du sprichst über Getränke, Essen, Wünsche und Verneinungen.",
        grammar = "مجھے ... پسند ہے drückt Vorlieben aus. چاہیے bedeutet brauchen oder möchten. نہیں steht gewöhnlich vor dem Verb.",
        dialogue = listOf(
            phrase("مجھے چائے پسند ہے۔", "mujhe chāe pasand hai.", "Ich mag Tee."),
            phrase("مجھے پانی چاہیے۔", "mujhe pānī chāhiye.", "Ich möchte Wasser."),
            phrase("یہ کھانا مزیدار ہے۔", "ye khānā mazedār hai.", "Dieses Essen ist lecker."),
            phrase("میں گوشت نہیں کھاتا۔", "main gosht nahīn khātā.", "Ich esse kein Fleisch."),
        ),
        vocabulary = listOf(
            phrase("پانی", "pānī", "Wasser"),
            phrase("چائے", "chāe", "Tee"),
            phrase("کافی", "kāfī", "Kaffee"),
            phrase("کھانا", "khānā", "Essen"),
            phrase("گوشت", "gosht", "Fleisch"),
            phrase("سبزی", "sabzī", "Gemüse"),
        ),
        questions = listOf(
            question("Wie sagst du Ich möchte Wasser?", "مجھے پانی چاہیے۔", "مجھے چائے پسند ہے۔", "یہ کھانا ہے۔", "چاہیے drückt Wunsch oder Bedarf aus."),
            question("Welches Wort verneint eine Aussage?", "نہیں", "کیا", "ہے", "نہیں bedeutet nicht."),
            question("Was bedeutet پانی?", "Wasser", "Tee", "Kaffee", "پانی bedeutet Wasser."),
        ),
    ),
    Lesson(
        id = 5,
        title = "Im Restaurant",
        urduTitle = "ریستوران میں",
        objective = "Du bestellst Essen und bittest höflich um Menü und Rechnung.",
        grammar = "Höfliche Bitten verwenden häufig دیجیے oder لے آئیے. کے لیے bedeutet für.",
        dialogue = listOf(
            phrase("دو افراد کے لیے ایک میز، براہ کرم۔", "do afrād ke liye ek mez, barāh-e-karam.", "Einen Tisch für zwei, bitte."),
            phrase("مینو دیجیے۔", "menu dījiye.", "Bitte die Speisekarte."),
            phrase("میں بریانی لوں گا۔", "main biryānī lūn gā.", "Ich nehme Biryani."),
            phrase("بل لے آئیے۔", "bill le āiye.", "Bringen Sie bitte die Rechnung."),
        ),
        vocabulary = listOf(
            phrase("میز", "mez", "Tisch"),
            phrase("مینو", "menu", "Speisekarte"),
            phrase("بل", "bill", "Rechnung"),
            phrase("بریانی", "biryānī", "Biryani"),
            phrase("مرچ", "mirch", "Chili"),
            phrase("براہ کرم", "barāh-e-karam", "bitte"),
        ),
        questions = listOf(
            question("Wie bittest du um die Rechnung?", "بل لے آئیے۔", "مینو دیجیے۔", "پانی چاہیے۔", "بل bedeutet Rechnung."),
            question("Was bedeutet میز?", "Tisch", "Stuhl", "Speisekarte", "میز bedeutet Tisch."),
            question("Welche Form bedeutet bitte?", "براہ کرم", "شکریہ", "خدا حافظ", "براہ کرم bedeutet bitte."),
        ),
    ),
)
