package com.estebvac.urdudeutsch

internal val lessonsSixToTen = listOf(
    Lesson(
        id = 6,
        title = "Hotel und Reise",
        urduTitle = "ہوٹل اور سفر",
        objective = "Du fragst nach Zimmer, Frühstück, Schlüssel und WLAN.",
        grammar = "Fragen enthalten oft کیا oder Fragewörter wie کہاں, کب und کتنا. خالی bedeutet frei oder verfügbar.",
        dialogue = listOf(
            phrase("کیا ایک کمرہ خالی ہے؟", "kyā ek kamrā khālī hai?", "Ist ein Zimmer frei?"),
            phrase("ایک رات کے لیے۔", "ek rāt ke liye.", "Für eine Nacht."),
            phrase("کیا ناشتہ شامل ہے؟", "kyā nāshta shāmil hai?", "Ist Frühstück inbegriffen?"),
            phrase("چابی کہاں ہے؟", "chābī kahān hai?", "Wo ist der Schlüssel?"),
        ),
        vocabulary = listOf(
            phrase("ہوٹل", "hotel", "Hotel"),
            phrase("کمرہ", "kamrā", "Zimmer"),
            phrase("چابی", "chābī", "Schlüssel"),
            phrase("رات", "rāt", "Nacht"),
            phrase("ناشتہ", "nāshta", "Frühstück"),
            phrase("خالی", "khālī", "frei / leer"),
        ),
        questions = listOf(
            question("Wie fragst du nach einem freien Zimmer?", "کیا ایک کمرہ خالی ہے؟", "کمرہ بڑا ہے۔", "ناشتہ کہاں ہے؟", "خالی bedeutet frei."),
            question("Was bedeutet چابی?", "Schlüssel", "Zimmer", "Frühstück", "چابی bedeutet Schlüssel."),
            question("Welches Wort bedeutet wo?", "کہاں", "کب", "کتنا", "کہاں bedeutet wo."),
        ),
    ),
    Lesson(
        id = 7,
        title = "Stadt und Verkehr",
        urduTitle = "شہر اور ٹریفک",
        objective = "Du fragst nach Orten und sprichst über Verkehrsmittel.",
        grammar = "Die Verlaufsform verwendet رہا، رہی oder رہے. Mit سے kann ein Verkehrsmittel markiert werden.",
        dialogue = listOf(
            phrase("ریلوے اسٹیشن کہاں ہے؟", "railway station kahān hai?", "Wo ist der Bahnhof?"),
            phrase("میں بس سے جا رہا ہوں۔", "main bus se jā rahā hūn.", "Ich fahre mit dem Bus."),
            phrase("بازار قریب ہے۔", "bāzār qarīb hai.", "Der Markt ist in der Nähe."),
            phrase("ایک ٹیکسی بلائیے۔", "ek taxi bulāiye.", "Rufen Sie bitte ein Taxi."),
        ),
        vocabulary = listOf(
            phrase("شہر", "shahr", "Stadt"),
            phrase("بازار", "bāzār", "Markt"),
            phrase("اسٹیشن", "station", "Bahnhof"),
            phrase("بس", "bus", "Bus"),
            phrase("ٹیکسی", "taxi", "Taxi"),
            phrase("قریب", "qarīb", "nah"),
        ),
        questions = listOf(
            question("Wie fragst du nach dem Bahnhof?", "ریلوے اسٹیشن کہاں ہے؟", "بازار قریب ہے۔", "ٹیکسی بلائیے۔", "کہاں fragt nach einem Ort."),
            question("Welche Postposition markiert hier das Verkehrsmittel?", "سے", "کا", "میں", "بس سے bedeutet mit dem Bus."),
            question("Was bedeutet قریب?", "nah", "weit", "links", "قریب bedeutet nah."),
        ),
    ),
    Lesson(
        id = 8,
        title = "Richtungen und Möglichkeiten",
        urduTitle = "راستہ اور امکان",
        objective = "Du verstehst Wegbeschreibungen und fragst, was möglich ist.",
        grammar = "سکنا drückt Fähigkeit oder Möglichkeit aus. Höfliche Anweisungen enden häufig auf یں.",
        dialogue = listOf(
            phrase("سیدھا جائیں۔", "sīdhā jāiye.", "Gehen Sie geradeaus."),
            phrase("بائیں مڑیں۔", "bāein muṛein.", "Biegen Sie links ab."),
            phrase("دائیں مڑیں۔", "dāein muṛein.", "Biegen Sie rechts ab."),
            phrase("کیا پیدل جا سکتے ہیں؟", "kyā paidal jā sakte hain?", "Kann man zu Fuß gehen?"),
        ),
        vocabulary = listOf(
            phrase("سیدھا", "sīdhā", "geradeaus"),
            phrase("بائیں", "bāein", "links"),
            phrase("دائیں", "dāein", "rechts"),
            phrase("پیدل", "paidal", "zu Fuß"),
            phrase("راستہ", "rāsta", "Weg"),
            phrase("رکنا", "ruknā", "anhalten"),
        ),
        questions = listOf(
            question("Was bedeutet بائیں مڑیں?", "Links abbiegen", "Rechts abbiegen", "Geradeaus gehen", "بائیں bedeutet links."),
            question("Welches Verb drückt Können aus?", "سکنا", "ہونا", "جانا", "سکنا bedeutet können."),
            question("Wie heißt zu Fuß?", "پیدل", "قریب", "سیدھا", "پیدل bedeutet zu Fuß."),
        ),
    ),
    Lesson(
        id = 9,
        title = "Zahlen, Uhrzeit und Wetter",
        urduTitle = "اعداد، وقت اور موسم",
        objective = "Du fragst nach Uhrzeit und sprichst über Tage und Wetter.",
        grammar = "Für Uhrzeiten steht بجے nach der Zahl. کل kann je nach Kontext gestern oder morgen bedeuten.",
        dialogue = listOf(
            phrase("کیا وقت ہوا ہے؟", "kyā waqt huā hai?", "Wie spät ist es?"),
            phrase("ساڑھے تین بجے ہیں۔", "sāṛhe tīn baje hain.", "Es ist halb vier."),
            phrase("آج موسم گرم ہے۔", "āj mausam garam hai.", "Heute ist es warm."),
            phrase("کل بارش ہوگی۔", "kal bārish hogī.", "Morgen wird es regnen."),
        ),
        vocabulary = listOf(
            phrase("وقت", "waqt", "Zeit"),
            phrase("آج", "āj", "heute"),
            phrase("کل", "kal", "gestern / morgen"),
            phrase("بارش", "bārish", "Regen"),
            phrase("موسم", "mausam", "Wetter"),
            phrase("گرم", "garam", "warm"),
        ),
        questions = listOf(
            question("Wie fragst du nach der Uhrzeit?", "کیا وقت ہوا ہے؟", "آج کیا ہے؟", "موسم گرم ہے؟", "وقت bedeutet Zeit."),
            question("Was bedeutet ساڑھے تین?", "halb vier", "drei Uhr", "halb drei", "ساڑھے تین entspricht 3:30 Uhr."),
            question("Welches Wort bedeutet Regen?", "بارش", "موسم", "گرم", "بارش bedeutet Regen."),
        ),
    ),
    Lesson(
        id = 10,
        title = "Einkaufen und Hobbys",
        urduTitle = "خریداری اور مشغلے",
        objective = "Du fragst nach Preisen und sprichst über Farben, Sport und Vorlieben.",
        grammar = "کتنے کا fragt nach dem Preis. Mit پسند ہے wird eine Vorliebe ausgedrückt.",
        dialogue = listOf(
            phrase("یہ کتنے کا ہے؟", "ye kitne kā hai?", "Wie viel kostet das?"),
            phrase("یہ بہت مہنگا ہے۔", "ye bahut mehngā hai.", "Das ist sehr teuer."),
            phrase("مجھے نیلا رنگ پسند ہے۔", "mujhe nīlā rang pasand hai.", "Ich mag Blau."),
            phrase("میں فٹ بال کھیلتا ہوں۔", "main football kheltā hūn.", "Ich spiele Fußball."),
        ),
        vocabulary = listOf(
            phrase("قیمت", "qīmat", "Preis"),
            phrase("مہنگا", "mehngā", "teuer"),
            phrase("سستا", "sastā", "günstig"),
            phrase("رنگ", "rang", "Farbe"),
            phrase("نیلا", "nīlā", "blau"),
            phrase("تیراکی", "tairākī", "Schwimmen"),
        ),
        questions = listOf(
            question("Wie fragst du nach dem Preis?", "یہ کتنے کا ہے؟", "یہ کہاں ہے؟", "کیا بڑا ہے؟", "کتنے کا fragt nach dem Preis."),
            question("Was bedeutet مہنگا?", "teuer", "günstig", "klein", "مہنگا bedeutet teuer."),
            question("Welche Aussage bedeutet Ich mag Blau?", "مجھے نیلا رنگ پسند ہے۔", "میں فٹ بال کھیلتا ہوں۔", "یہ بہت مہنگا ہے۔", "پسند ہے drückt Gefallen aus."),
        ),
    ),
)
